#!/usr/bin/perl -w

use encoding 'utf8';

use strict;
use warnings;
use diagnostics;
use HTMLPage;
use Benchmark::Timer;


my $html = <<HTML;
<table cellpadding='0' cellspacing='0' width='100%'>
<tr>

<tr><td style='color: #FFFFFF;font-size: 16;text-align: center;'><div  ><div class="dulezite">Magnetická kostka <a href="http://unimagnet.cz/20-k-d5-neocube-216kusu.html" title="NeoCube - magnetické kuličky a 3D puzzle">NeoCube</a>|Rychlá a profesionální <a href="http://www.tuev-nord.cz" title="Certifikace">certifikace</a> výrobních postupů|Profesionální <a href="http://www.cisty-domov.com" title="Chemie do bazénů">bazénová chemie</a> bez chléru|Nábytek, <a href="http://zidle.lino.cz" title="LINO židle">židle</a> a nábytkové doplňky na lino.cz|<a href="http://www.ploty-betafence.cz" title="Ploty Betafence">Ploty</a>, pletiva a oplocení od světového výrobce plotů</div></div> </endora><a href='http://celulitida.g6.cz' target=''>Zbavte se celulitidy. Celulitida, odtu�n�n�. Svitavy.</a></td></tr>

<tr><td style='color: #FFFFFF;font-size: 16;text-align: center;'><br>==============================================================================================<br>Vitejte na strance verejneho fora KVH Chocen
<br>
<h3><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /><a href='http://kvhchocen.g6.cz' target=''>ZDE vstupte na webovou prezentaci KVH Chocen</a><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /></h3><br></td></tr>
<td style='position:absolute;
font-size: 16;
top:40;
color: 050505;
font-weight: bold;
margin-top: 2px;
margin-bottom: 3px;
text-align: center;'></td>

</tr>
</table>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="cs-cz" xml:lang="cs-cz">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="cs-cz" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />

<title>KVH Choceň - Feldgendarmerie Trupp 82 &bull; Obsah</title>

<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:

	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Napište číslo stránky, na kterou chcete přejít:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var onload_functions = new Array();
	var onunload_functions = new Array();



	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/AZ_Retro/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/AZ_Retro/template/forum_fn.js"></script>

    <!--[if lt IE 7]>
    <script defer type="text/javascript" src="./styles/AZ_Retro/template/pngfix.js"></script>
    <![endif]-->

<link href="./styles/AZ_Retro/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?id=6&amp;lang=cs&amp;sid=e55570b3acff9f3e87742280f261561e" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/AZ_Retro/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/AZ_Retro/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/AZ_Retro/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />



</head>

<body id="phpbb" class="section-index ltr">

<div id="wrap">
  pepek
  ľščťžýáíéíáťžčťášň§ô§ú
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner">

			<div id="site-description">
				<a href="./index.php?sid=e55570b3acff9f3e87742280f261561e" title="Obsah fóra" id="logo"><img src="./styles/AZ_Retro/imageset/logo.png" width="400" height="120" alt="" title="" /></a>
				<p style="display: none;"><a href="#start_here">Přejít na obsah</a></p>
			</div>



			</div>

			<div id="movsitedesc">
			<h4>KVH Choceň - Feldgendarmerie Trupp 82</h4>
				<p></p>
			</div>

			<div id="movlinks">
			<ul class="linklist rightside colorfix">



				<li><a href="./faq.php?sid=e55570b3acff9f3e87742280f261561e" title="Často kladené otázky">FAQ</a> &bull; </li>
				<li><a href="./ucp.php?mode=register&amp;sid=e55570b3acff9f3e87742280f261561e">Registrovat</a> &bull;</li>
					<li><a href="./ucp.php?mode=login&amp;sid=e55570b3acff9f3e87742280f261561e" title="Přihlásit se" accesskey="l">Přihlásit se</a></li>

			</ul>
			</div>

		</div>

		<div class="navbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<ul class="linklist navlinks colorfix">
				<li class="icon-home"><a href="./index.php?sid=e55570b3acff9f3e87742280f261561e" accesskey="h">Obsah fóra</a> </li>

				<li class="rightside colorfix"><a href="#" onclick="fontsizeup(); return false;" onkeypress="fontsizeup(); return false;" class="fontsize" title="Změnit velikost textu">Změnit velikost textu</a></li>


			</ul>


			<span class="corners-bottom"><span></span></span></div>
		</div>

	</div>

	<a name="start_here"></a>
	<div id="page-body">



<p class="right">Právě je 18 lis 2011 12:13</p>

		<div class="forabg">
			<div class="inner"><span class="corners-top"><span></span></span>
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt>Fórum</dt>
						<dd class="topics">Témata</dd>
						<dd class="posts">Příspěvky</dd>
						<dd class="lastpost"><span>Poslední příspěvek</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=9&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Základní informace, pravidla, questbook apod.</a><br />
					<a href="http://www.toplist.cz/stat/1190842" target="_top"><img
src="http://toplist.cz/count.asp?id=1190842&logo=s" border="0" alt="TOPlist" width="14" height="14"/></a>

				</dt>

					<dd class="topics">3 <dfn>Témata</dfn></dd>
					<dd class="posts">3 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=2&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">Prunelle</a>
						<a href="./viewtopic.php?f=9&amp;p=13&amp;sid=e55570b3acff9f3e87742280f261561e#p13"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 03 úno 2011 22:10</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=18&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Feldgendarmerie - Polní četnictvo</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/cetnici.jpg" alt="Obrázek" /><br />Vše, co se týká jednotek polního četnictva...

				</dt>

					<dd class="topics">7 <dfn>Témata</dfn></dd>
					<dd class="posts">11 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=55&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">hans</a>
						<a href="./viewtopic.php?f=18&amp;p=816&amp;sid=e55570b3acff9f3e87742280f261561e#p816"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 05 zář 2011 07:30</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=11&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Fotografie</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/fotografie.jpg" alt="Obrázek" /><br />Fotografie dobové, barevné i retro...

				</dt>

					<dd class="topics">6 <dfn>Témata</dfn></dd>
					<dd class="posts">20 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=2&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">Prunelle</a>
						<a href="./viewtopic.php?f=11&amp;p=650&amp;sid=e55570b3acff9f3e87742280f261561e#p650"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 14 črc 2011 18:41</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=12&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Videa</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/videa.jpg" alt="Obrázek" /><br />Videa od uživatelů...

				</dt>

					<dd class="topics">10 <dfn>Témata</dfn></dd>
					<dd class="posts">31 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=55&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">hans</a>
						<a href="./viewtopic.php?f=12&amp;p=528&amp;sid=e55570b3acff9f3e87742280f261561e#p528"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 08 čer 2011 15:48</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=13&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Články</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/clanky.jpg" alt="Obrázek" /><br />Různé články a další materiály...

				</dt>

					<dd class="topics">3 <dfn>Témata</dfn></dd>
					<dd class="posts">7 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=2&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">Prunelle</a>
						<a href="./viewtopic.php?f=13&amp;p=651&amp;sid=e55570b3acff9f3e87742280f261561e#p651"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 14 črc 2011 18:42</span>
					</dd>

			</dl>
		</li>

			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>

	<form method="post" action="./ucp.php?mode=login&amp;sid=e55570b3acff9f3e87742280f261561e" class="headerspace">
	<h3><a href="./ucp.php?mode=login&amp;sid=e55570b3acff9f3e87742280f261561e">Přihlásit se</a>&nbsp; &bull; &nbsp;<a href="./ucp.php?mode=register&amp;sid=e55570b3acff9f3e87742280f261561e">Registrovat</a></h3>
		<fieldset class="quick-login">
			<label for="username">Uživatelské jméno:</label>&nbsp;<input type="text" name="username" id="username" size="10" class="inputbox" title="Uživatelské jméno" />
			<label for="password">Heslo:</label>&nbsp;<input type="password" name="password" id="password" size="10" class="inputbox" title="Heslo" />

				| <label for="autologin">Přihlásit mě automaticky při každé návštěvě <input type="checkbox" name="autologin" id="autologin" /></label>

			<input type="submit" name="login" value="Přihlásit se" class="button2" />
		</fieldset>
	</form>
<h3>Kdo je online</h3>
	<p>Celkem je online <strong>2</strong> uživatelů :: 0 registrovaných, 0 skrytých a 2 návštěvníků (Tato data jsou založena na uživatelích, kteří byli aktivní za posledních 5 minut)<br />Nejvíce zde současně bylo přítomno <strong>10</strong> uživatelů dne 07 čer 2011 17:44<br /> <br />Registrovaní uživatelé: Žádní registrovaní uživatelé
	<br /><em>Legenda: <a style="color:#AA0000" href="./memberlist.php?mode=group&amp;g=5&amp;sid=e55570b3acff9f3e87742280f261561e">Administrátoři</a>, <a style="color:#00AA00" href="./memberlist.php?mode=group&amp;g=4&amp;sid=e55570b3acff9f3e87742280f261561e">Globální moderátoři</a>, <a style="color:#FF6600" href="./memberlist.php?mode=group&amp;g=8&amp;sid=e55570b3acff9f3e87742280f261561e">KVH Choceň</a></em></p>

	<h3>Statistiky</h3>
	<p>Celkem příspěvků <strong>534</strong> &bull; Celkem témat <strong>87</strong> &bull; Celkem členů <strong>15</strong> &bull; Nejnovějším uživatelem je <strong><a href="./memberlist.php?mode=viewprofile&amp;u=151&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">BernardG</a></strong></p>
<div class="navbar">
		<div class="inner"><span class="corners-top"><span></span></span>

		<ul class="linklist colorfix">
			<li class="icon-home"><a href="./index.php?sid=e55570b3acff9f3e87742280f261561e" accesskey="h">Obsah fóra</a></li>

			<li class="rightside"><a href="./memberlist.php?mode=leaders&amp;sid=e55570b3acff9f3e87742280f261561e">Tým</a> &bull; <a href="./ucp.php?mode=delete_cookies&amp;sid=e55570b3acff9f3e87742280f261561e">Smazat všechny cookies z fóra</a> &bull; Všechny časy jsou v&nbsp;UTC + 1 hodina [ Letní čas ]</li>
		</ul>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	</div>

<div id="page-footer">

<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	<div class="copyright colorfix">Powered by <a href="http://www.phpbb.com/">phpBB</a> &copy; 2000, 2002, 2005, 2007 phpBB Group
	<br />
	PhpBB Skin <b>AZ Retro</b> by ayasha &copy; 2008 <a href="http://www.white-fusion.com/forum/">White Fusion Skins</a><br />
	<br />
		<br />Český překlad – <a href="http://www.phpbb.cz/">phpBB.cz</a>
	</div>
</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>

</div>

</body>
</html>
HTML

my $replacements = {
  'pepek' => '<a href="pepekovo">{keyword}</a>',
  'ľščťžýáíéíáťžčťášň§ô§ú' => '<a href="pepekovo">{keyword}</a>',
  '2011 (2012) bydlení kalkulačka na příspě' => '<a href="pepekovo">{keyword}</a>',
  '2011 bydlení kalkulačka na příspě' => '<a href="pepekovo">{keyword}</a>',
  '3D architekt' => '<a href="pepekovo">{keyword}</a>',
  'Adidas' => '<a href="pepekovo">{keyword}</a>',
  'adidas boty' => '<a href="pepekovo">{keyword}</a>',
  'adidas damske soupravy' => '<a href="pepekovo">{keyword}</a>',
  'adidas dámské teplákové soupravy' => '<a href="pepekovo">{keyword}</a>',
  'Adidas Lady' => '<a href="pepekovo">{keyword}</a>',
  'adidas mikiny' => '<a href="pepekovo">{keyword}</a>',
  'adidas originals' => '<a href="pepekovo">{keyword}</a>',
  'adidas soupravy' => '<a href="pepekovo">{keyword}</a>',
  'adidas superstar' => '<a href="pepekovo">{keyword}</a>',
  'adidas trička' => '<a href="pepekovo">{keyword}</a>',
  'aminokyseliny' => '<a href="pepekovo">{keyword}</a>',
  'architektura' => '<a href="pepekovo">{keyword}</a>',
  'architektura barokní' => '<a href="pepekovo">{keyword}</a>',
  'architektura bytová' => '<a href="pepekovo">{keyword}</a>',
  'architektura domu' => '<a href="pepekovo">{keyword}</a>',
  'architektura lidová' => '<a href="pepekovo">{keyword}</a>',
  'architektura moderní' => '<a href="pepekovo">{keyword}</a>',
  'architektura zahradní' => '<a href="pepekovo">{keyword}</a>',
  'architektura zahrady' => '<a href="pepekovo">{keyword}</a>',
  'autopůjčovna' => '<a href="pepekovo">{keyword}</a>',
  'autopůjčovna Brno' => '<a href="pepekovo">{keyword}</a>',
  'autopůjčovna Olomouc' => '<a href="pepekovo">{keyword}</a>',
  'autopůjčovna Ostrava' => '<a href="pepekovo">{keyword}</a>',
  'autopůjčovna Praha' => '<a href="pepekovo">{keyword}</a>',
  'autoškola Praha' => '<a href="pepekovo">{keyword}</a>',
  'barové židle' => '<a href="pepekovo">{keyword}</a>',
  'bavlněné ponožky, ponožky' => '<a href="pepekovo">{keyword}</a>',
  'bazénová chemie' => '<a href="pepekovo">{keyword}</a>',
  'bcaa' => '<a href="pepekovo">{keyword}</a>',
  'bělení zubů' => '<a href="pepekovo">{keyword}</a>',
  'bělení zubů brno' => '<a href="pepekovo">{keyword}</a>',
  'blank & basic' => '<a href="pepekovo">{keyword}</a>',
  'bomber bunda' => '<a href="pepekovo">{keyword}</a>',
  'botanická zahrada' => '<a href="pepekovo">{keyword}</a>',
  'botičky pro miminka' => '<a href="pepekovo">{keyword}</a>',
  'bydlení' => '<a href="pepekovo">{keyword}</a>',
  'bydlení je hra' => '<a href="pepekovo">{keyword}</a>',
  'bytové interiéry' => '<a href="pepekovo">{keyword}</a>',
  'carnitin' => '<a href="pepekovo">{keyword}</a>',
  'catering' => '<a href="pepekovo">{keyword}</a>',
  'ceny webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'certifikace' => '<a href="pepekovo">{keyword}</a>',
  'certifikace iso' => '<a href="pepekovo">{keyword}</a>',
  'čepice' => '<a href="pepekovo">{keyword}</a>',
  'čočky' => '<a href="pepekovo">{keyword}</a>',
  'Dada Supreme' => '<a href="pepekovo">{keyword}</a>',
  'Dada Supreme Lady' => '<a href="pepekovo">{keyword}</a>',
  'Dada Supreme Performance' => '<a href="pepekovo">{keyword}</a>',
  'dámská móda' => '<a href="pepekovo">{keyword}</a>',
  'dámská obuv' => '<a href="pepekovo">{keyword}</a>',
  'dámská trička' => '<a href="pepekovo">{keyword}</a>',
  'Dámská trička dlouhý rukáv' => '<a href="pepekovo">{keyword}</a>',
  'Dámské boty' => '<a href="pepekovo">{keyword}</a>',
  'dámské bundy' => '<a href="pepekovo">{keyword}</a>',
  'dámské doplňky' => '<a href="pepekovo">{keyword}</a>',
  'Dámské džíny' => '<a href="pepekovo">{keyword}</a>',
  'Dámské hodinky' => '<a href="pepekovo">{keyword}</a>',
  'dámské kalhoty' => '<a href="pepekovo">{keyword}</a>',
  'Dámské košile' => '<a href="pepekovo">{keyword}</a>',
  'Dámské kožené bundy' => '<a href="pepekovo">{keyword}</a>',
  'dámské levné mikiny' => '<a href="pepekovo">{keyword}</a>',
  'dámské mikiny' => '<a href="pepekovo">{keyword}</a>',
  'Dámské mikiny s kapucí' => '<a href="pepekovo">{keyword}</a>',
  'dámské mikiny výprodej' => '<a href="pepekovo">{keyword}</a>',
  'dámské oblečení' => '<a href="pepekovo">{keyword}</a>',
  'dámské peněženky' => '<a href="pepekovo">{keyword}</a>',
  'dámské plážové oblečení' => '<a href="pepekovo">{keyword}</a>',
  'Dámské pletené svetry' => '<a href="pepekovo">{keyword}</a>',
  'dámské soupravy' => '<a href="pepekovo">{keyword}</a>',
  'Dámské spodní prádlo' => '<a href="pepekovo">{keyword}</a>',
  'Dámské svetry' => '<a href="pepekovo">{keyword}</a>',
  'dámské šátky' => '<a href="pepekovo">{keyword}</a>',
  'dámské šaty' => '<a href="pepekovo">{keyword}</a>',
  'Dámské teplákové soupravy' => '<a href="pepekovo">{keyword}</a>',
  'dámské tepláky' => '<a href="pepekovo">{keyword}</a>',
  'Dámské vesty' => '<a href="pepekovo">{keyword}</a>',
  'dámské zimní boty' => '<a href="pepekovo">{keyword}</a>',
  'Dámské zimní bundy' => '<a href="pepekovo">{keyword}</a>',
  'dámské zimní bundy 2011' => '<a href="pepekovo">{keyword}</a>',
  'dámské zimní bundy výprodej' => '<a href="pepekovo">{keyword}</a>',
  'dámské zimní kabátky' => '<a href="pepekovo">{keyword}</a>',
  'dámské zimní kabáty' => '<a href="pepekovo">{keyword}</a>',
  'dámské zimní kozačky' => '<a href="pepekovo">{keyword}</a>',
  'dentální hygiena' => '<a href="pepekovo">{keyword}</a>',
  'dentální hygiena brno' => '<a href="pepekovo">{keyword}</a>',
  'design webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'děti, dětské oblečení' => '<a href="pepekovo">{keyword}</a>',
  'dětská móda' => '<a href="pepekovo">{keyword}</a>',
  'dětská optika' => '<a href="pepekovo">{keyword}</a>',
  'dětské botičky' => '<a href="pepekovo">{keyword}</a>',
  'dětské boty' => '<a href="pepekovo">{keyword}</a>',
  'dětské brýle' => '<a href="pepekovo">{keyword}</a>',
  'dětské čepice' => '<a href="pepekovo">{keyword}</a>',
  'Dětské kalhoty' => '<a href="pepekovo">{keyword}</a>',
  'dětské mikiny' => '<a href="pepekovo">{keyword}</a>',
  'dětské oblečení' => '<a href="pepekovo">{keyword}</a>',
  'dětské ponožky' => '<a href="pepekovo">{keyword}</a>',
  'Dětské spodní prádlo' => '<a href="pepekovo">{keyword}</a>',
  'dětské zimní boty' => '<a href="pepekovo">{keyword}</a>',
  'Dětské zimní čepice, dětské čepice' => '<a href="pepekovo">{keyword}</a>',
  'dětské zimní oblečení' => '<a href="pepekovo">{keyword}</a>',
  'domény' => '<a href="pepekovo">{keyword}</a>',
  'dotace pro podnikatele' => '<a href="pepekovo">{keyword}</a>',
  'dotace z EU' => '<a href="pepekovo">{keyword}</a>',
  'endodoncie brno' => '<a href="pepekovo">{keyword}</a>',
  'famous stars' => '<a href="pepekovo">{keyword}</a>',
  'famous stars and straps' => '<a href="pepekovo">{keyword}</a>',
  'firemní akce' => '<a href="pepekovo">{keyword}</a>',
  'firemní web' => '<a href="pepekovo">{keyword}</a>',
  'fitness' => '<a href="pepekovo">{keyword}</a>',
  'fitness Praha 2' => '<a href="pepekovo">{keyword}</a>',
  'Fráze' => '<a href="pepekovo">{keyword}</a>',
  'grafický návrh webu' => '<a href="pepekovo">{keyword}</a>',
  'hip hop' => '<a href="pepekovo">{keyword}</a>',
  'hip hop kšiltovky' => '<a href="pepekovo">{keyword}</a>',
  'hip hop oblečení' => '<a href="pepekovo">{keyword}</a>',
  'hip hop Praha' => '<a href="pepekovo">{keyword}</a>',
  'hip hop shop' => '<a href="pepekovo">{keyword}</a>',
  'hip hop shop nejlevnější' => '<a href="pepekovo">{keyword}</a>',
  'hip hop teplákové soupravy' => '<a href="pepekovo">{keyword}</a>',
  'hoodboyz' => '<a href="pepekovo">{keyword}</a>',
  'hoodboyz soupravy' => '<a href="pepekovo">{keyword}</a>',
  'hoodboyz tepláky' => '<a href="pepekovo">{keyword}</a>',
  'hovno' => '<a href="pepekovo">{keyword}</a>',
  'hra' => '<a href="pepekovo">{keyword}</a>',
  'hypotéka' => '<a href="pepekovo">{keyword}</a>',
  'ikea kuchyně' => '<a href="pepekovo">{keyword}</a>',
  'interiéry' => '<a href="pepekovo">{keyword}</a>',
  'interiéry bytů' => '<a href="pepekovo">{keyword}</a>',
  'interiéry fotogalerie' => '<a href="pepekovo">{keyword}</a>',
  'interiéry ložnic' => '<a href="pepekovo">{keyword}</a>',
  'interiéry moderní' => '<a href="pepekovo">{keyword}</a>',
  'interiéry obyvacích pokojů' => '<a href="pepekovo">{keyword}</a>',
  'internetové stránky zdarma' => '<a href="pepekovo">{keyword}</a>',
  'Jack & Jones' => '<a href="pepekovo">{keyword}</a>',
  'jak si vytvořit webové stránky' => '<a href="pepekovo">{keyword}</a>',
  'jak vytvořit internetové stránky' => '<a href="pepekovo">{keyword}</a>',
  'jak vytvořit internetovou stránku' => '<a href="pepekovo">{keyword}</a>',
  'jak vytvořit www stránky' => '<a href="pepekovo">{keyword}</a>',
  'jazykové kurzy Brno' => '<a href="pepekovo">{keyword}</a>',
  'jednoduchá tvorba webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'jednoduché webové stránky' => '<a href="pepekovo">{keyword}</a>',
  'jesličky brno' => '<a href="pepekovo">{keyword}</a>',
  'kalhoty sportovní' => '<a href="pepekovo">{keyword}</a>',
  'kavitace' => '<a href="pepekovo">{keyword}</a>',
  'kniha' => '<a href="pepekovo">{keyword}</a>',
  'kojenecké oblečení' => '<a href="pepekovo">{keyword}</a>',
  'kojenecké soupravy' => '<a href="pepekovo">{keyword}</a>',
  'kojenecké zimní oblečení' => '<a href="pepekovo">{keyword}</a>',
  'kondiční jízdy' => '<a href="pepekovo">{keyword}</a>',
  'kontaktní čočky' => '<a href="pepekovo">{keyword}</a>',
  'kosmetické studio' => '<a href="pepekovo">{keyword}</a>',
  'koupelny' => '<a href="pepekovo">{keyword}</a>',
  'koupelny Brno' => '<a href="pepekovo">{keyword}</a>',
  'koupelny fotogalerie' => '<a href="pepekovo">{keyword}</a>',
  'koupelny inspirace' => '<a href="pepekovo">{keyword}</a>',
  'kožené bundy' => '<a href="pepekovo">{keyword}</a>',
  'kožené rukavice' => '<a href="pepekovo">{keyword}</a>',
  'křesla' => '<a href="pepekovo">{keyword}</a>',
  'kšiltovky' => '<a href="pepekovo">{keyword}</a>',
  'kuchyně' => '<a href="pepekovo">{keyword}</a>',
  'kuchyně fotogalerie' => '<a href="pepekovo">{keyword}</a>',
  'kuchyně levně' => '<a href="pepekovo">{keyword}</a>',
  'kuchyně rustikalní' => '<a href="pepekovo">{keyword}</a>',
  'kurzy angličtiny Brno' => '<a href="pepekovo">{keyword}</a>',
  'květinářství Brno' => '<a href="pepekovo">{keyword}</a>',
  'laboratoře' => '<a href="pepekovo">{keyword}</a>',
  'letní šaty' => '<a href="pepekovo">{keyword}</a>',
  'levné mikiny' => '<a href="pepekovo">{keyword}</a>',
  'levné oblečení' => '<a href="pepekovo">{keyword}</a>',
  'levné webové stránky' => '<a href="pepekovo">{keyword}</a>',
  'levné zimní bundy' => '<a href="pepekovo">{keyword}</a>',
  'luxusní dětské oblečení' => '<a href="pepekovo">{keyword}</a>',
  'luxusní pánské hodinky' => '<a href="pepekovo">{keyword}</a>',
  'masáže Praha' => '<a href="pepekovo">{keyword}</a>',
  'matrace' => '<a href="pepekovo">{keyword}</a>',
  'mikiny' => '<a href="pepekovo">{keyword}</a>',
  'mikiny nike' => '<a href="pepekovo">{keyword}</a>',
  'mikiny s kapuci' => '<a href="pepekovo">{keyword}</a>',
  'mikiny výprodej' => '<a href="pepekovo">{keyword}</a>',
  'mp3' => '<a href="pepekovo">{keyword}</a>',
  'nábytek' => '<a href="pepekovo">{keyword}</a>',
  'nábytek Brno' => '<a href="pepekovo">{keyword}</a>',
  'nábytek z masivu' => '<a href="pepekovo">{keyword}</a>',
  'nákupní centrum' => '<a href="pepekovo">{keyword}</a>',
  'nejlevnější hip hop shop' => '<a href="pepekovo">{keyword}</a>',
  'německé cestovní kanceláře' => '<a href="pepekovo">{keyword}</a>',
  'New Era' => '<a href="pepekovo">{keyword}</a>',
  'new era kšiltovky' => '<a href="pepekovo">{keyword}</a>',
  'novorozenencké oblečení' => '<a href="pepekovo">{keyword}</a>',
  'nutrend' => '<a href="pepekovo">{keyword}</a>',
  'objektivy' => '<a href="pepekovo">{keyword}</a>',
  'obklady do koupelny' => '<a href="pepekovo">{keyword}</a>',
  'obklady do kuchyně' => '<a href="pepekovo">{keyword}</a>',
  'oblečení' => '<a href="pepekovo">{keyword}</a>',
  'obuv' => '<a href="pepekovo">{keyword}</a>',
  'ocelové šperky' => '<a href="pepekovo">{keyword}</a>',
  'oční lékař' => '<a href="pepekovo">{keyword}</a>',
  'okno' => '<a href="pepekovo">{keyword}</a>',
  'oplocení' => '<a href="pepekovo">{keyword}</a>',
  'optika' => '<a href="pepekovo">{keyword}</a>',
  'outdoor bundy' => '<a href="pepekovo">{keyword}</a>',
  'outsourcing IT' => '<a href="pepekovo">{keyword}</a>',
  'pánská móda' => '<a href="pepekovo">{keyword}</a>',
  'pánská móda 2011' => '<a href="pepekovo">{keyword}</a>',
  'pánská obuv' => '<a href="pepekovo">{keyword}</a>',
  'pánská tílka' => '<a href="pepekovo">{keyword}</a>',
  'pánská trička' => '<a href="pepekovo">{keyword}</a>',
  'pánské boty' => '<a href="pepekovo">{keyword}</a>',
  'pánské boxerky' => '<a href="pepekovo">{keyword}</a>',
  'pánské bundy' => '<a href="pepekovo">{keyword}</a>',
  'pánské čepice' => '<a href="pepekovo">{keyword}</a>',
  'pánské doplňky' => '<a href="pepekovo">{keyword}</a>',
  'pánské džíny' => '<a href="pepekovo">{keyword}</a>',
  'pánské kalhoty' => '<a href="pepekovo">{keyword}</a>',
  'pánské košile' => '<a href="pepekovo">{keyword}</a>',
  'pánské kotníkové boty' => '<a href="pepekovo">{keyword}</a>',
  'pánské kožené bundy' => '<a href="pepekovo">{keyword}</a>',
  'pánské kšiltovky' => '<a href="pepekovo">{keyword}</a>',
  'pánské luxusní košile' => '<a href="pepekovo">{keyword}</a>',
  'pánské mikiny' => '<a href="pepekovo">{keyword}</a>',
  'pánské mikiny se zipem' => '<a href="pepekovo">{keyword}</a>',
  'pánské náramky' => '<a href="pepekovo">{keyword}</a>',
  'pánské oblečení' => '<a href="pepekovo">{keyword}</a>',
  'pánské opasky' => '<a href="pepekovo">{keyword}</a>',
  'pánské peněženky' => '<a href="pepekovo">{keyword}</a>',
  'pánské ponožky' => '<a href="pepekovo">{keyword}</a>',
  'pánské soupravy' => '<a href="pepekovo">{keyword}</a>',
  'pánské spodní prádlo' => '<a href="pepekovo">{keyword}</a>',
  'pánské společenské boty' => '<a href="pepekovo">{keyword}</a>',
  'pánské svetry' => '<a href="pepekovo">{keyword}</a>',
  'pánské šály' => '<a href="pepekovo">{keyword}</a>',
  'pánské teplákové soupravy' => '<a href="pepekovo">{keyword}</a>',
  'pánské tepláky' => '<a href="pepekovo">{keyword}</a>',
  'pánské trenýrky' => '<a href="pepekovo">{keyword}</a>',
  'pánské vesty' => '<a href="pepekovo">{keyword}</a>',
  'pánské větrovky' => '<a href="pepekovo">{keyword}</a>',
  'pánské zimní boty' => '<a href="pepekovo">{keyword}</a>',
  'pánské zimní bundy' => '<a href="pepekovo">{keyword}</a>',
  'pánské zimní kabáty' => '<a href="pepekovo">{keyword}</a>',
  'permanentní make-up' => '<a href="pepekovo">{keyword}</a>',
  'plážové oblečení' => '<a href="pepekovo">{keyword}</a>',
  'plážové šaty' => '<a href="pepekovo">{keyword}</a>',
  'pletené čepice' => '<a href="pepekovo">{keyword}</a>',
  'pletené svetry' => '<a href="pepekovo">{keyword}</a>',
  'pletené šály' => '<a href="pepekovo">{keyword}</a>',
  'pletivo' => '<a href="pepekovo">{keyword}</a>',
  'ploty' => '<a href="pepekovo">{keyword}</a>',
  'podzimní bundy' => '<a href="pepekovo">{keyword}</a>',
  'podzimní vesty' => '<a href="pepekovo">{keyword}</a>',
  'porno' => '<a href="pepekovo">{keyword}</a>',
  'posilovací stroje' => '<a href="pepekovo">{keyword}</a>',
  'povinné ručení' => '<a href="pepekovo">{keyword}</a>',
  'práce' => '<a href="pepekovo">{keyword}</a>',
  'praha' => '<a href="pepekovo">{keyword}</a>',
  'privátní sauna' => '<a href="pepekovo">{keyword}</a>',
  'privátní vířivka' => '<a href="pepekovo">{keyword}</a>',
  'privátní whirlpool' => '<a href="pepekovo">{keyword}</a>',
  'prodej bytů Praha' => '<a href="pepekovo">{keyword}</a>',
  'profesionální webdesign' => '<a href="pepekovo">{keyword}</a>',
  'program na tvorbu webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'programy pro tvorbu webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'projekční kancelář' => '<a href="pepekovo">{keyword}</a>',
  'projektová dokumentace' => '<a href="pepekovo">{keyword}</a>',
  'projektování staveb' => '<a href="pepekovo">{keyword}</a>',
  'pronájem eshopu' => '<a href="pepekovo">{keyword}</a>',
  'proteinové nápoje' => '<a href="pepekovo">{keyword}</a>',
  'proteiny' => '<a href="pepekovo">{keyword}</a>',
  'příspěvek na bydlení' => '<a href="pepekovo">{keyword}</a>',
  'ptáci' => '<a href="pepekovo">{keyword}</a>',
  'půjčka' => '<a href="pepekovo">{keyword}</a>',
  'půjčovna aut' => '<a href="pepekovo">{keyword}</a>',
  'půjčovna aut Brno' => '<a href="pepekovo">{keyword}</a>',
  'půjčovna aut Olomouc' => '<a href="pepekovo">{keyword}</a>',
  'půjčovna aut Ostrava' => '<a href="pepekovo">{keyword}</a>',
  'půjčovna aut Praha' => '<a href="pepekovo">{keyword}</a>',
  'Raw Blue' => '<a href="pepekovo">{keyword}</a>',
  'reklamní agentura' => '<a href="pepekovo">{keyword}</a>',
  'restaurace Brno' => '<a href="pepekovo">{keyword}</a>',
  'rotopedy' => '<a href="pepekovo">{keyword}</a>',
  'sauna Praha' => '<a href="pepekovo">{keyword}</a>',
  'spalovače tuků' => '<a href="pepekovo">{keyword}</a>',
  'sportovní kalhoty' => '<a href="pepekovo">{keyword}</a>',
  'sportovní oblečení' => '<a href="pepekovo">{keyword}</a>',
  'sportovní obuv' => '<a href="pepekovo">{keyword}</a>',
  'správa nemovitosti' => '<a href="pepekovo">{keyword}</a>',
  'správa nemovitosti Brno' => '<a href="pepekovo">{keyword}</a>',
  'správa sítě Brno' => '<a href="pepekovo">{keyword}</a>',
  'správa webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'správa webu' => '<a href="pepekovo">{keyword}</a>',
  'stativy' => '<a href="pepekovo">{keyword}</a>',
  'stavební dozor' => '<a href="pepekovo">{keyword}</a>',
  'stk Praha' => '<a href="pepekovo">{keyword}</a>',
  'stolové nohy' => '<a href="pepekovo">{keyword}</a>',
  'stolové podnože' => '<a href="pepekovo">{keyword}</a>',
  'stoly' => '<a href="pepekovo">{keyword}</a>',
  'stomatologie' => '<a href="pepekovo">{keyword}</a>',
  'stomatologie Brno' => '<a href="pepekovo">{keyword}</a>',
  'street dance Praha' => '<a href="pepekovo">{keyword}</a>',
  'stříbrné šperky' => '<a href="pepekovo">{keyword}</a>',
  'sushi' => '<a href="pepekovo">{keyword}</a>',
  'šablony webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'šály a šátky' => '<a href="pepekovo">{keyword}</a>',
  'šátky na hlavu' => '<a href="pepekovo">{keyword}</a>',
  'šátky na krk' => '<a href="pepekovo">{keyword}</a>',
  'šperky' => '<a href="pepekovo">{keyword}</a>',
  'tandemový seskok' => '<a href="pepekovo">{keyword}</a>',
  'taneční škola Praha' => '<a href="pepekovo">{keyword}</a>',
  'technický dozor investora' => '<a href="pepekovo">{keyword}</a>',
  'teplákové soupravy' => '<a href="pepekovo">{keyword}</a>',
  'teplákové soupravy akce' => '<a href="pepekovo">{keyword}</a>',
  'tepláky' => '<a href="pepekovo">{keyword}</a>',
  'termoprádlo' => '<a href="pepekovo">{keyword}</a>',
  'trička' => '<a href="pepekovo">{keyword}</a>',
  'tvorba eshopu' => '<a href="pepekovo">{keyword}</a>',
  'tvorba internetových stránek' => '<a href="pepekovo">{keyword}</a>',
  'tvorba internetových stránek zdarma' => '<a href="pepekovo">{keyword}</a>',
  'tvorba stránek zdarma' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webové stránky' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek cena' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek ceník' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek levně' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek návod' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek pro začátečníky' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek program' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek s administrací' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webových stránek zdarma' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webu ceník' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webu online' => '<a href="pepekovo">{keyword}</a>',
  'tvorba webu zdarma' => '<a href="pepekovo">{keyword}</a>',
  'tvorba www stránek' => '<a href="pepekovo">{keyword}</a>',
  'tvorba www stránek ceník' => '<a href="pepekovo">{keyword}</a>',
  'tvorba www stránek zdarma' => '<a href="pepekovo">{keyword}</a>',
  'tvorba www zdarma' => '<a href="pepekovo">{keyword}</a>',
  'tvoření webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'ubytování' => '<a href="pepekovo">{keyword}</a>',
  'ubytování Šumava' => '<a href="pepekovo">{keyword}</a>',
  'udržba zeleně' => '<a href="pepekovo">{keyword}</a>',
  'úklid Brno' => '<a href="pepekovo">{keyword}</a>',
  'vany do koupelny' => '<a href="pepekovo">{keyword}</a>',
  'Vero Moda' => '<a href="pepekovo">{keyword}</a>',
  'video' => '<a href="pepekovo">{keyword}</a>',
  'víno' => '<a href="pepekovo">{keyword}</a>',
  'výprodej oblečení' => '<a href="pepekovo">{keyword}</a>',
  'vytváření webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'vytvoření stránek' => '<a href="pepekovo">{keyword}</a>',
  'vytvoření webové stránky' => '<a href="pepekovo">{keyword}</a>',
  'vytvoření webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'vytvoření webových stránek zdarma' => '<a href="pepekovo">{keyword}</a>',
  'vytvoření www stránek' => '<a href="pepekovo">{keyword}</a>',
  'vytvořit webové stránky' => '<a href="pepekovo">{keyword}</a>',
  'výuka angličtiny Brno' => '<a href="pepekovo">{keyword}</a>',
  'web stranky tvorba' => '<a href="pepekovo">{keyword}</a>',
  'web stranky zadarmo' => '<a href="pepekovo">{keyword}</a>',
  'web stránky zdarma' => '<a href="pepekovo">{keyword}</a>',
  'web šablona' => '<a href="pepekovo">{keyword}</a>',
  'webová stránka zdarma' => '<a href="pepekovo">{keyword}</a>',
  'webové prezentace' => '<a href="pepekovo">{keyword}</a>',
  'webové stránky ceník' => '<a href="pepekovo">{keyword}</a>',
  'webové stránky s administrací' => '<a href="pepekovo">{keyword}</a>',
  'webové šablony' => '<a href="pepekovo">{keyword}</a>',
  'weby zdarma' => '<a href="pepekovo">{keyword}</a>',
  'wellness Praha' => '<a href="pepekovo">{keyword}</a>',
  'www stránky levně' => '<a href="pepekovo">{keyword}</a>',
  'zahrada' => '<a href="pepekovo">{keyword}</a>',
  'zahradní domek' => '<a href="pepekovo">{keyword}</a>',
  'zahradní domky' => '<a href="pepekovo">{keyword}</a>',
  'zahradní jezírka' => '<a href="pepekovo">{keyword}</a>',
  'zahradní krby' => '<a href="pepekovo">{keyword}</a>',
  'zahradní nábytek' => '<a href="pepekovo">{keyword}</a>',
  'zahradní technika' => '<a href="pepekovo">{keyword}</a>',
  'zahradní traktory' => '<a href="pepekovo">{keyword}</a>',
  'založení webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'zážitky jako dárek' => '<a href="pepekovo">{keyword}</a>',
  'zdravotní matrace' => '<a href="pepekovo">{keyword}</a>',
  'zhotovení webových stránek' => '<a href="pepekovo">{keyword}</a>',
  'zimní boty' => '<a href="pepekovo">{keyword}</a>',
  'zimní bunda' => '<a href="pepekovo">{keyword}</a>',
  'zimní bundy' => '<a href="pepekovo">{keyword}</a>',
  'zimní bundy 2011' => '<a href="pepekovo">{keyword}</a>',
  'zimní bundy výprodej' => '<a href="pepekovo">{keyword}</a>',
  'zimní čepice' => '<a href="pepekovo">{keyword}</a>',
  'zimní dámské čepice' => '<a href="pepekovo">{keyword}</a>',
  'zimní dětské čepice' => '<a href="pepekovo">{keyword}</a>',
  'zimní kožené bundy' => '<a href="pepekovo">{keyword}</a>',
  'zimní oblečení' => '<a href="pepekovo">{keyword}</a>',
  'zimní obuv' => '<a href="pepekovo">{keyword}</a>',
  'zimní rukavice' => '<a href="pepekovo">{keyword}</a>',
  'zimní vesty' => '<a href="pepekovo">{keyword}</a>',
  'zimní zahrada' => '<a href="pepekovo">{keyword}</a>',
  'značkové mikiny' => '<a href="pepekovo">{keyword}</a>',
  'značkové oblečení' => '<a href="pepekovo">{keyword}</a>',
  'značkové teplákové soupravy' => '<a href="pepekovo">{keyword}</a>',
  'zubař brno' => '<a href="pepekovo">{keyword}</a>',
  'zubní ordinace' => '<a href="pepekovo">{keyword}</a>',
  'zubní ordinace Brno' => '<a href="pepekovo">{keyword}</a>',
  'židle' => '<a href="pepekovo">{keyword}</a>',
};

my $timer = Benchmark::Timer->new();

$timer->start('creating page');
my $page = HTMLPage->from_string($html);
$timer->stop;

$timer->start('parsing words');
$page->replace($replacements);
$timer->stop;
$timer->report;

$html = $page->get_html();
print $html;
