#!/usr/bin/perl -w

use encoding 'utf8';

use strict;
use warnings;
use diagnostics;
use HTMLPage;


my $html = <<HTML;
<table cellpadding='0' cellspacing='0' width='100%'>
<tr>

<tr><td style='color: #FFFFFF;font-size: 16;text-align: center;'><div  ><div class="dulezite">Magnetická kostka <a href="http://unimagnet.cz/20-k-d5-neocube-216kusu.html" title="NeoCube - magnetické kuličky a 3D puzzle">NeoCube</a>|Rychlá a profesionální <a href="http://www.tuev-nord.cz" title="Certifikace">certifikace</a> výrobních postupů|Profesionální <a href="http://www.cisty-domov.com" title="Chemie do bazénů">bazénová chemie</a> bez chléru|Nábytek, <a href="http://zidle.lino.cz" title="LINO židle">židle</a> a nábytkové doplňky na lino.cz|<a href="http://www.ploty-betafence.cz" title="Ploty Betafence">Ploty</a>, pletiva a oplocení od světového výrobce plotů</div></div> </endora><a href='http://celulitida.g6.cz' target=''>Zbavte se celulitidy. Celulitida, odtu�n�n�. Svitavy.</a></td></tr>

<tr><td style='color: #FFFFFF;font-size: 16;text-align: center;'><br>==============================================================================================<br>Vitejte na strance verejneho fora KVH Chocen
<br>
<h3><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /><a href='http://kvhchocen.g6.cz' target=''>ZDE vstupte na webovou prezentaci KVH Chocen</a><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /><img src='http://forumkvhchocen.g6.cz/images/smilies/icon_exclaim.gif' /></h3><br></td></tr>
<td style='position:absolute;
font-size: 16;
top:40;
color: 050505;
font-weight: bold;
margin-top: 2px;
margin-bottom: 3px;
text-align: center;'></td>

</tr>
</table>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="cs-cz" xml:lang="cs-cz">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="cs-cz" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />

<title>KVH Choceň - Feldgendarmerie Trupp 82 &bull; Obsah</title>

<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:

	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Napište číslo stránky, na kterou chcete přejít:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var onload_functions = new Array();
	var onunload_functions = new Array();



	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/AZ_Retro/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/AZ_Retro/template/forum_fn.js"></script>

    <!--[if lt IE 7]>
    <script defer type="text/javascript" src="./styles/AZ_Retro/template/pngfix.js"></script>
    <![endif]-->

<link href="./styles/AZ_Retro/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?id=6&amp;lang=cs&amp;sid=e55570b3acff9f3e87742280f261561e" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/AZ_Retro/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/AZ_Retro/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/AZ_Retro/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />



</head>

<body id="phpbb" class="section-index ltr">

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner">

			<div id="site-description">
				<a href="./index.php?sid=e55570b3acff9f3e87742280f261561e" title="Obsah fóra" id="logo"><img src="./styles/AZ_Retro/imageset/logo.png" width="400" height="120" alt="" title="" /></a>
				<p style="display: none;"><a href="#start_here">Přejít na obsah</a></p>
			</div>



			</div>

			<div id="movsitedesc">
			<h4>KVH Choceň - Feldgendarmerie Trupp 82</h4>
				<p></p>
			</div>

			<div id="movlinks">
			<ul class="linklist rightside colorfix">



				<li><a href="./faq.php?sid=e55570b3acff9f3e87742280f261561e" title="Často kladené otázky">FAQ</a> &bull; </li>
				<li><a href="./ucp.php?mode=register&amp;sid=e55570b3acff9f3e87742280f261561e">Registrovat</a> &bull;</li>
					<li><a href="./ucp.php?mode=login&amp;sid=e55570b3acff9f3e87742280f261561e" title="Přihlásit se" accesskey="l">Přihlásit se</a></li>

			</ul>
			</div>

		</div>

		<div class="navbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<ul class="linklist navlinks colorfix">
				<li class="icon-home"><a href="./index.php?sid=e55570b3acff9f3e87742280f261561e" accesskey="h">Obsah fóra</a> </li>

				<li class="rightside colorfix"><a href="#" onclick="fontsizeup(); return false;" onkeypress="fontsizeup(); return false;" class="fontsize" title="Změnit velikost textu">Změnit velikost textu</a></li>


			</ul>


			<span class="corners-bottom"><span></span></span></div>
		</div>

	</div>

	<a name="start_here"></a>
	<div id="page-body">



<p class="right">Právě je 18 lis 2011 12:13</p>

		<div class="forabg">
			<div class="inner"><span class="corners-top"><span></span></span>
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt>Fórum</dt>
						<dd class="topics">Témata</dd>
						<dd class="posts">Příspěvky</dd>
						<dd class="lastpost"><span>Poslední příspěvek</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=9&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Základní informace, pravidla, questbook apod.</a><br />
					<a href="http://www.toplist.cz/stat/1190842" target="_top"><img
src="http://toplist.cz/count.asp?id=1190842&logo=s" border="0" alt="TOPlist" width="14" height="14"/></a>

				</dt>

					<dd class="topics">3 <dfn>Témata</dfn></dd>
					<dd class="posts">3 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=2&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">Prunelle</a>
						<a href="./viewtopic.php?f=9&amp;p=13&amp;sid=e55570b3acff9f3e87742280f261561e#p13"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 03 úno 2011 22:10</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=18&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Feldgendarmerie - Polní četnictvo</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/cetnici.jpg" alt="Obrázek" /><br />Vše, co se týká jednotek polního četnictva...

				</dt>

					<dd class="topics">7 <dfn>Témata</dfn></dd>
					<dd class="posts">11 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=55&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">hans</a>
						<a href="./viewtopic.php?f=18&amp;p=816&amp;sid=e55570b3acff9f3e87742280f261561e#p816"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 05 zář 2011 07:30</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=11&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Fotografie</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/fotografie.jpg" alt="Obrázek" /><br />Fotografie dobové, barevné i retro...

				</dt>

					<dd class="topics">6 <dfn>Témata</dfn></dd>
					<dd class="posts">20 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=2&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">Prunelle</a>
						<a href="./viewtopic.php?f=11&amp;p=650&amp;sid=e55570b3acff9f3e87742280f261561e#p650"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 14 črc 2011 18:41</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=12&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Videa</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/videa.jpg" alt="Obrázek" /><br />Videa od uživatelů...

				</dt>

					<dd class="topics">10 <dfn>Témata</dfn></dd>
					<dd class="posts">31 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=55&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">hans</a>
						<a href="./viewtopic.php?f=12&amp;p=528&amp;sid=e55570b3acff9f3e87742280f261561e#p528"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 08 čer 2011 15:48</span>
					</dd>

			</dl>
		</li>

		<li class="row">
			<dl class="icon" style="background-image: url(./styles/AZ_Retro/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="Žádné nové příspěvky">

					<a href="./viewforum.php?f=13&amp;sid=e55570b3acff9f3e87742280f261561e" class="forumtitle">Články</a><br />
					<img src="http://forumkvhchocen.g6.cz/images/clanky.jpg" alt="Obrázek" /><br />Různé články a další materiály...

				</dt>

					<dd class="topics">3 <dfn>Témata</dfn></dd>
					<dd class="posts">7 <dfn>Příspěvky</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Poslední příspěvek</dfn> od <a href="./memberlist.php?mode=viewprofile&amp;u=2&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">Prunelle</a>
						<a href="./viewtopic.php?f=13&amp;p=651&amp;sid=e55570b3acff9f3e87742280f261561e#p651"><img src="./styles/AZ_Retro/imageset/icon_topic_latest.gif" width="11" height="9" alt="Zobrazit poslední příspěvek" title="Zobrazit poslední příspěvek" /></a> <br />v 14 črc 2011 18:42</span>
					</dd>

			</dl>
		</li>

			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>

	<form method="post" action="./ucp.php?mode=login&amp;sid=e55570b3acff9f3e87742280f261561e" class="headerspace">
	<h3><a href="./ucp.php?mode=login&amp;sid=e55570b3acff9f3e87742280f261561e">Přihlásit se</a>&nbsp; &bull; &nbsp;<a href="./ucp.php?mode=register&amp;sid=e55570b3acff9f3e87742280f261561e">Registrovat</a></h3>
		<fieldset class="quick-login">
			<label for="username">Uživatelské jméno:</label>&nbsp;<input type="text" name="username" id="username" size="10" class="inputbox" title="Uživatelské jméno" />
			<label for="password">Heslo:</label>&nbsp;<input type="password" name="password" id="password" size="10" class="inputbox" title="Heslo" />

				| <label for="autologin">Přihlásit mě automaticky při každé návštěvě <input type="checkbox" name="autologin" id="autologin" /></label>

			<input type="submit" name="login" value="Přihlásit se" class="button2" />
		</fieldset>
	</form>
<h3>Kdo je online</h3>
	<p>Celkem je online <strong>2</strong> uživatelů :: 0 registrovaných, 0 skrytých a 2 návštěvníků (Tato data jsou založena na uživatelích, kteří byli aktivní za posledních 5 minut)<br />Nejvíce zde současně bylo přítomno <strong>10</strong> uživatelů dne 07 čer 2011 17:44<br /> <br />Registrovaní uživatelé: Žádní registrovaní uživatelé
	<br /><em>Legenda: <a style="color:#AA0000" href="./memberlist.php?mode=group&amp;g=5&amp;sid=e55570b3acff9f3e87742280f261561e">Administrátoři</a>, <a style="color:#00AA00" href="./memberlist.php?mode=group&amp;g=4&amp;sid=e55570b3acff9f3e87742280f261561e">Globální moderátoři</a>, <a style="color:#FF6600" href="./memberlist.php?mode=group&amp;g=8&amp;sid=e55570b3acff9f3e87742280f261561e">KVH Choceň</a></em></p>

	<h3>Statistiky</h3>
	<p>Celkem příspěvků <strong>534</strong> &bull; Celkem témat <strong>87</strong> &bull; Celkem členů <strong>15</strong> &bull; Nejnovějším uživatelem je <strong><a href="./memberlist.php?mode=viewprofile&amp;u=151&amp;sid=e55570b3acff9f3e87742280f261561e" style="color: #FF6600;" class="username-coloured">BernardG</a></strong></p>
<div class="navbar">
		<div class="inner"><span class="corners-top"><span></span></span>

		<ul class="linklist colorfix">
			<li class="icon-home"><a href="./index.php?sid=e55570b3acff9f3e87742280f261561e" accesskey="h">Obsah fóra</a></li>

			<li class="rightside"><a href="./memberlist.php?mode=leaders&amp;sid=e55570b3acff9f3e87742280f261561e">Tým</a> &bull; <a href="./ucp.php?mode=delete_cookies&amp;sid=e55570b3acff9f3e87742280f261561e">Smazat všechny cookies z fóra</a> &bull; Všechny časy jsou v&nbsp;UTC + 1 hodina [ Letní čas ]</li>
		</ul>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	</div>

<div id="page-footer">

<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	<div class="copyright colorfix">Powered by <a href="http://www.phpbb.com/">phpBB</a> &copy; 2000, 2002, 2005, 2007 phpBB Group
	<br />
	PhpBB Skin <b>AZ Retro</b> by ayasha &copy; 2008 <a href="http://www.white-fusion.com/forum/">White Fusion Skins</a><br />
	<br />
		<br />Český překlad – <a href="http://www.phpbb.cz/">phpBB.cz</a>
	</div>
</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>

</div>

</body>
</html>
HTML

my %replacements = (
  'ľščťžýÁÍéééééíážťčšťľšýžť' => '<a href="pepekovo">{keyword}</a>',
  'pÁtek' => '<a href="den">{keyword}</a>',
  'nedráždí pokožku' => '<a href="pepekovo">{keyword}</a>',
  'jop' => '<a href="pepekovo">{keyword}</a>',
);

my $MAX_REPLACEMENTS_COUNT = 1;


my $word = '';
my $page = HTMLPage->from_string($html);
foreach $word (keys %replacements) {
  $page->replace($word, $replacements{$word});
  if($page->{'replacements_count'} >= $MAX_REPLACEMENTS_COUNT) {
    last;
  }
}
$html = $page->get_html();

print $html;
